drop table if exists entradas;
create table entradas (
  id integer primary key autoincrement,
  linha de pesquisa,
  nome string,
  pai string,
  mae string,
  cpf string,
  birthdate string,
  sexo string,
  nacionalidade string,
  pais string,
  anochegada string,
  logradouro string,
  numero string,
  complemento string,
  bairro string,
  municipio string,
  UF string,
  cep integer,
  telcasa integer,
  celular int
  email string,
  tempo string,
  justificativa string,
  justificativaoutros string,
  empresa string,
  funcao string,
  telefoneempresa string,
  emailempresa string,
  rg string,
  dattarg string,
  orgaorg string,
  estadorg string,
  faculdade string,
  curso string,
  estadocurso string,
  anoconclusao string,
  cartainteresse string
  
  
);
